"""change is possible

Revision ID: 4ba1e8c7b35d
Revises: 968b800e8a3e
Create Date: 2025-01-09 11:41:18.759731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ba1e8c7b35d'
down_revision: Union[str, None] = '968b800e8a3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_blog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_blog',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('blog_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], name='user_blog_blog_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_blog_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'blog_id', name='user_blog_pkey')
    )
    # ### end Alembic commands ###
